#!/bin/bash
# Tiny colored fetch script
# Requires Typicons Font to display the icons
# elenapan @ github

LC_ALL=C
LANG=C

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'

# Items
sep=
s=$d$f0$sep$t

h=
phn="$(getprop ro.product.model)"

k=
kernel="$(uname -r | cut -d '-' -f1)"

sh=
shell=$(basename $SHELL)

r=
pkgs="$(apt list --installed 2>/dev/null | wc -l)"

w=
uptime="$(uptime --pretty | sed 's/up//')"

# (\ /)
# ( · ·)
# c(")(")

# (\ /)
# ( . .)
# c(")(")

clear
cat << EOF

             $d$f1$h  $t$phn
   (\ /)     $f3$k  $t$kernel
   ( $d. .$t)    $f2$sh  $t$shell
   c($f1"$t)($f1"$t)   $f5$r  $t$pkgs
             $f4$w $t$uptime

EOF
